---
- name: install elasticsearch
  hosts: elasticsearch
  become: true
  become_method: sudo

  tasks:
  - name: install java
    yum:
      name: java-1.8.0-openjdk 
      state: present

  - name: copy elasticsearch repo
    copy:
      src: files/elasticsearch.repo
      dest: /etc/yum.repos.d/elasticsearch.repo

  - name: install elasticsearch
    yum:
      name: elasticsearch
      state: present
    
  - name: change listen adress
    lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      state: present
      regexp: "^#network.host"
      line: "network.host: 0.0.0.0"

  - name: uncomment port
    lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      state: present
      regexp: "^#http.port"
      line: "http.port: 9200"

  - name: Start elasticsearch
    service:
      name: elasticsearch
      state: restarted
      enabled: yes