---
- name: install kibana
  hosts: kibana
  become: true
  become_method: sudo

  tasks:
  - name: copy elk repo
    copy:
      src: files/elasticsearch.repo
      dest: /etc/yum.repos.d/elasticsearch.repo
    
  - name: install kibana
    yum:
      name: kibana
      state: present
     
  - name: start & enable kibana
    service:
      name: kibana
      state: restarted
      enabled: yes