---
- name: install kibana
  hosts: kibana
  become: true
  become_method: sudo

  tasks:
  - name: copy elk repo
    copy:
      src: files/elasticsearch.repo
      dest: /etc/yum.repos.d/elasticsearch.repo
    
  - name: install kibana
    yum:
      name: kibana
      state: present

  - name: copy config file
    template:
      src: kibana.yml.j2
      dest: /etc/kibana/kibana.yml
    
     
  - name: start & enable kibana
    service:
      name: kibana
      state: restarted
      enabled: yes