---
- name: delete nginx
  hosts: server
  become: true
  become_method: sudo

  tasks:
  - name: Del epel-release repo
    yum:
      name: epel-release
      state: absent

  - name: Del nginx
    yum:
      name: nginx
      state: absent
