---
- name: Install nginx
  hosts: kibana
  become: true
  become_method: sudo

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: delete default index
    file:
      path: /usr/share/nginx/html/index.html
      state: absent

  - name: change default config file
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    
  - name: config nginx to serve kibana
    template:
      src: kibana.conf.j2
      dest: /etc/nginx/conf.d/kibana.conf

  - name: Start NGiNX
    service:
      name: nginx
      state: started   
      enabled: yes
