---
- name: install rsyslog
  hosts: rsyslog_server
  become: true
  become_method: sudo

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install rsyslog
    yum:
      name: rsyslog
      state: present

  - name: disable selinux
    lineinfile:
      path: /etc/sysconfig/selinux
      state: present
      regexp: "^SELINUX"
      line: "SELINUX=disabled"

  - name: copy config file
    template:
      src: rsyslog.conf.j2
      dest: /etc/rsyslog.conf
  
  - name: start & enable rsyslog
    service:
      name: rsyslog
      state: restarted
      enabled: yes